// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: protofiles/logistica.proto

package protofiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminarConexionMensaje struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *TerminarConexionMensaje) Reset() {
	*x = TerminarConexionMensaje{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_logistica_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminarConexionMensaje) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminarConexionMensaje) ProtoMessage() {}

func (x *TerminarConexionMensaje) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_logistica_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminarConexionMensaje.ProtoReflect.Descriptor instead.
func (*TerminarConexionMensaje) Descriptor() ([]byte, []int) {
	return file_protofiles_logistica_proto_rawDescGZIP(), []int{0}
}

func (x *TerminarConexionMensaje) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Mensaje para enviar un nuevo paquete
type PackageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete   string `protobuf:"bytes,1,opt,name=id_paquete,json=idPaquete,proto3" json:"id_paquete,omitempty"`
	Timestamp   int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tipo        string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nombre      string `protobuf:"bytes,4,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Valor       int32  `protobuf:"varint,5,opt,name=valor,proto3" json:"valor,omitempty"`
	Escolta     string `protobuf:"bytes,6,opt,name=escolta,proto3" json:"escolta,omitempty"`
	Destino     string `protobuf:"bytes,7,opt,name=destino,proto3" json:"destino,omitempty"`
	Seguimiento string `protobuf:"bytes,8,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
}

func (x *PackageRequest) Reset() {
	*x = PackageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_logistica_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageRequest) ProtoMessage() {}

func (x *PackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_logistica_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageRequest.ProtoReflect.Descriptor instead.
func (*PackageRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_logistica_proto_rawDescGZIP(), []int{1}
}

func (x *PackageRequest) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

func (x *PackageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PackageRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *PackageRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *PackageRequest) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *PackageRequest) GetEscolta() string {
	if x != nil {
		return x.Escolta
	}
	return ""
}

func (x *PackageRequest) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *PackageRequest) GetSeguimiento() string {
	if x != nil {
		return x.Seguimiento
	}
	return ""
}

// Respuesta de la solicitud de envío de paquete
type PackageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seguimiento string `protobuf:"bytes,1,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
	Estado      string `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *PackageResponse) Reset() {
	*x = PackageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_logistica_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageResponse) ProtoMessage() {}

func (x *PackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_logistica_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageResponse.ProtoReflect.Descriptor instead.
func (*PackageResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_logistica_proto_rawDescGZIP(), []int{2}
}

func (x *PackageResponse) GetSeguimiento() string {
	if x != nil {
		return x.Seguimiento
	}
	return ""
}

func (x *PackageResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

// Solicitud de estado de paquete
type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seguimiento string `protobuf:"bytes,1,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_logistica_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_logistica_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_logistica_proto_rawDescGZIP(), []int{3}
}

func (x *StatusRequest) GetSeguimiento() string {
	if x != nil {
		return x.Seguimiento
	}
	return ""
}

// Respuesta con el estado del paquete
type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete string `protobuf:"bytes,1,opt,name=id_paquete,json=idPaquete,proto3" json:"id_paquete,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tipo      string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Destino   string `protobuf:"bytes,4,opt,name=destino,proto3" json:"destino,omitempty"`
	Valor     int32  `protobuf:"varint,5,opt,name=valor,proto3" json:"valor,omitempty"`
	Escolta   string `protobuf:"bytes,6,opt,name=escolta,proto3" json:"escolta,omitempty"`
	Estado    string `protobuf:"bytes,7,opt,name=estado,proto3" json:"estado,omitempty"`
	Intentos  int32  `protobuf:"varint,8,opt,name=intentos,proto3" json:"intentos,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_logistica_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_logistica_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_logistica_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

func (x *StatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StatusResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *StatusResponse) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *StatusResponse) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *StatusResponse) GetEscolta() string {
	if x != nil {
		return x.Escolta
	}
	return ""
}

func (x *StatusResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *StatusResponse) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

// Solicitud para actualizar el estado de la entrega desde la caravana a logistica
type DeliveryUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete   string `protobuf:"bytes,1,opt,name=id_paquete,json=idPaquete,proto3" json:"id_paquete,omitempty"`
	Seguimiento string `protobuf:"bytes,2,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
	Tipo        string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor       int32  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Intentos    int32  `protobuf:"varint,5,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Estado      string `protobuf:"bytes,6,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *DeliveryUpdateRequest) Reset() {
	*x = DeliveryUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_logistica_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryUpdateRequest) ProtoMessage() {}

func (x *DeliveryUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_logistica_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryUpdateRequest.ProtoReflect.Descriptor instead.
func (*DeliveryUpdateRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_logistica_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryUpdateRequest) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

func (x *DeliveryUpdateRequest) GetSeguimiento() string {
	if x != nil {
		return x.Seguimiento
	}
	return ""
}

func (x *DeliveryUpdateRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *DeliveryUpdateRequest) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *DeliveryUpdateRequest) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *DeliveryUpdateRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type DeliveryUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *DeliveryUpdateResponse) Reset() {
	*x = DeliveryUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_logistica_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryUpdateResponse) ProtoMessage() {}

func (x *DeliveryUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_logistica_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryUpdateResponse.ProtoReflect.Descriptor instead.
func (*DeliveryUpdateResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_logistica_proto_rawDescGZIP(), []int{6}
}

func (x *DeliveryUpdateResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Mensaje para enviar instrucciones de reparto a las caravanas
type DeliveryInstructionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packages []*PackageRequest `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
}

func (x *DeliveryInstructionRequest) Reset() {
	*x = DeliveryInstructionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_logistica_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryInstructionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryInstructionRequest) ProtoMessage() {}

func (x *DeliveryInstructionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_logistica_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryInstructionRequest.ProtoReflect.Descriptor instead.
func (*DeliveryInstructionRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_logistica_proto_rawDescGZIP(), []int{7}
}

func (x *DeliveryInstructionRequest) GetPackages() []*PackageRequest {
	if x != nil {
		return x.Packages
	}
	return nil
}

// Nuevo mensaje para representar el resultado de una entrega
type DeliveryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete string `protobuf:"bytes,1,opt,name=id_paquete,json=idPaquete,proto3" json:"id_paquete,omitempty"`
	Exito     bool   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
	Intentos  int32  `protobuf:"varint,3,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Valor     int32  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (x *DeliveryResult) Reset() {
	*x = DeliveryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_logistica_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResult) ProtoMessage() {}

func (x *DeliveryResult) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_logistica_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResult.ProtoReflect.Descriptor instead.
func (*DeliveryResult) Descriptor() ([]byte, []int) {
	return file_protofiles_logistica_proto_rawDescGZIP(), []int{8}
}

func (x *DeliveryResult) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

func (x *DeliveryResult) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *DeliveryResult) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *DeliveryResult) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

// Respuesta de las caravanas al recibir las instrucciones de reparto
type DeliveryInstructionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*DeliveryResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // Lista de resultados de las entregas
}

func (x *DeliveryInstructionResponse) Reset() {
	*x = DeliveryInstructionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_logistica_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryInstructionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryInstructionResponse) ProtoMessage() {}

func (x *DeliveryInstructionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_logistica_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryInstructionResponse.ProtoReflect.Descriptor instead.
func (*DeliveryInstructionResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_logistica_proto_rawDescGZIP(), []int{9}
}

func (x *DeliveryInstructionResponse) GetResults() []*DeliveryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_protofiles_logistica_proto protoreflect.FileDescriptor

var file_protofiles_logistica_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x6c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x33, 0x0a, 0x17, 0x54, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x65, 0x78, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22, 0xe5, 0x01,
	0x0a, 0x0e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x73, 0x63, 0x6f, 0x6c, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x73, 0x63, 0x6f, 0x6c, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0f, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x75,
	0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73,
	0x74, 0x61, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x22, 0x31, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0xdf, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x70,
	0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64,
	0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x73, 0x63,
	0x6f, 0x6c, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x73, 0x63, 0x6f,
	0x6c, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x22, 0xb6, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x22, 0x32, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e,
	0x73, 0x61, 0x6a, 0x65, 0x22, 0x54, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x22, 0x77, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x64, 0x5f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x78, 0x69, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x74,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x22, 0x53, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32, 0x80, 0x02, 0x0a, 0x0d, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x53, 0x65,
	0x6e, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a,
	0x10, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x65, 0x78, 0x69, 0x6f,
	0x6e, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x54,
	0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x65, 0x78, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x65,
	0x78, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x32, 0xd6, 0x01, 0x0a, 0x0e,
	0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x54, 0x61, 0x72, 0x65, 0x61, 0x31, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protofiles_logistica_proto_rawDescOnce sync.Once
	file_protofiles_logistica_proto_rawDescData = file_protofiles_logistica_proto_rawDesc
)

func file_protofiles_logistica_proto_rawDescGZIP() []byte {
	file_protofiles_logistica_proto_rawDescOnce.Do(func() {
		file_protofiles_logistica_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_logistica_proto_rawDescData)
	})
	return file_protofiles_logistica_proto_rawDescData
}

var file_protofiles_logistica_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protofiles_logistica_proto_goTypes = []any{
	(*TerminarConexionMensaje)(nil),     // 0: protofiles.TerminarConexionMensaje
	(*PackageRequest)(nil),              // 1: protofiles.PackageRequest
	(*PackageResponse)(nil),             // 2: protofiles.PackageResponse
	(*StatusRequest)(nil),               // 3: protofiles.StatusRequest
	(*StatusResponse)(nil),              // 4: protofiles.StatusResponse
	(*DeliveryUpdateRequest)(nil),       // 5: protofiles.DeliveryUpdateRequest
	(*DeliveryUpdateResponse)(nil),      // 6: protofiles.DeliveryUpdateResponse
	(*DeliveryInstructionRequest)(nil),  // 7: protofiles.DeliveryInstructionRequest
	(*DeliveryResult)(nil),              // 8: protofiles.DeliveryResult
	(*DeliveryInstructionResponse)(nil), // 9: protofiles.DeliveryInstructionResponse
}
var file_protofiles_logistica_proto_depIdxs = []int32{
	1, // 0: protofiles.DeliveryInstructionRequest.packages:type_name -> protofiles.PackageRequest
	8, // 1: protofiles.DeliveryInstructionResponse.results:type_name -> protofiles.DeliveryResult
	1, // 2: protofiles.ClientService.SendPackage:input_type -> protofiles.PackageRequest
	3, // 3: protofiles.ClientService.GetPackageStatus:input_type -> protofiles.StatusRequest
	0, // 4: protofiles.ClientService.TerminarConexion:input_type -> protofiles.TerminarConexionMensaje
	5, // 5: protofiles.CaravanService.UpdateDelivery:input_type -> protofiles.DeliveryUpdateRequest
	7, // 6: protofiles.CaravanService.SendDeliveryInstructions:input_type -> protofiles.DeliveryInstructionRequest
	2, // 7: protofiles.ClientService.SendPackage:output_type -> protofiles.PackageResponse
	4, // 8: protofiles.ClientService.GetPackageStatus:output_type -> protofiles.StatusResponse
	0, // 9: protofiles.ClientService.TerminarConexion:output_type -> protofiles.TerminarConexionMensaje
	6, // 10: protofiles.CaravanService.UpdateDelivery:output_type -> protofiles.DeliveryUpdateResponse
	9, // 11: protofiles.CaravanService.SendDeliveryInstructions:output_type -> protofiles.DeliveryInstructionResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protofiles_logistica_proto_init() }
func file_protofiles_logistica_proto_init() {
	if File_protofiles_logistica_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_logistica_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TerminarConexionMensaje); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_logistica_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PackageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_logistica_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PackageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_logistica_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_logistica_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_logistica_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeliveryUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_logistica_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeliveryUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_logistica_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeliveryInstructionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_logistica_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeliveryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_logistica_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeliveryInstructionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_logistica_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protofiles_logistica_proto_goTypes,
		DependencyIndexes: file_protofiles_logistica_proto_depIdxs,
		MessageInfos:      file_protofiles_logistica_proto_msgTypes,
	}.Build()
	File_protofiles_logistica_proto = out.File
	file_protofiles_logistica_proto_rawDesc = nil
	file_protofiles_logistica_proto_goTypes = nil
	file_protofiles_logistica_proto_depIdxs = nil
}
